- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  head-widgets:
      - type: search
        autofocus: true
        search-engine: google
        new-tab: true
      - type: markets
        markets:
          - symbol: INTC
            name: Intel
          - symbol: RKLB
            name: Rocket Lab
          - symbol: PNG.V
            name: Kraken Robotics
          - symbol: MSFT
            name: Microsoft
          - symbol: XEQT.TO
            name: iShares Core Equity ETF Portfolio

  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
            - url: https://ciechanow.ski/atom.xml
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed

    - size: full
      widgets:
        - type: server-stats
          title: Server
          servers:
            - type: local
              name: Server Ubuntu
              hide-mountpoints-by-default: true
              mountpoints:
                "/":
                  name: Root
                  hide: false
            - type: remote
              name: Linux Mint
              url: http://100.75.26.76:27973
              icon: si:linuxmint
              timeout: 10s
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Application tracker
              url: https://web.starb.ca
              icon: https://web.starb.ca/spike.svg
            - title: Maxim's blog
              url: https://maxim.starb.ca
              icon: si:ghost
            - title: n8n
              url: https://n8n.starb.ca
              icon: si:n8n
            - title: Bloxtr8
              url: https://pilot.bloxtr8.com
              icon: https://bloxtr8.com/icon.svg
            - title: Bloxtr8 landing page
              url: https://bloxtr8.com
              icon: https://bloxtr8.com/icon.svg
            - title: F1 API
              url: https://f1-api.starb.ca/f1/next_race/
              icon: si:f1
            - title: Stremio server
              url: https://stremio.starb.ca
              icon: si:stremio
            - title: passbolt
              url: https://passbolt.starb.ca
              icon: si:passbolt
        - type: docker-containers
          hide-by-default: false

        - type: custom-api
          title: Tailscale Devices
          title-url: https://login.tailscale.com/admin/machines
          url: https://api.tailscale.com/api/v2/tailnet/-/devices
          headers:
            Authorization: Bearer ${TAILSCALE_API_KEY}
          cache: 10m
          options:
            collapseAfter: 10
            # disableOfflineIndicator: true
            disableUpdateIndicator: true
            # prioritiseTags: true
          template: |
            <style>
              .device-info-container-tailscale {
                position: relative;
                overflow: hidden;
                height: 1.5em;
              }

              .device-info-tailscale {
                display: flex;
                transition: transform 0.2s ease, opacity 0.2s ease;
              }

              .device-ip-tailscale {
                position: absolute;
                top: 0;
                left: 0;
                transform: translateY(-100%);
                opacity: 0;
                transition: transform 0.2s ease, opacity 0.2s ease;
              }

              .device-info-container-tailscale:hover .device-info-tailscale {
                transform: translateY(100%);
                opacity: 0;
              }

              .device-info-container-tailscale:hover .device-ip-tailscale {
                transform: translateY(0);
                opacity: 1;
              }

              .update-indicator-tailscale {
                width: 8px;
                height: 8px;
                border-radius: 50%;
                background-color: var(--color-primary);
                display: inline-block;
                margin-left: 4px;
                vertical-align: middle;
              }

              .offline-indicator-tailscale {
                width: 8px;
                height: 8px;
                border-radius: 50%;
                background-color: var(--color-negative);
                display: inline-block;
                margin-left: 4px;
                vertical-align: middle;
              }

              .device-name-container-tailscale {
                display: flex;
                align-items: center;
                gap: 8px;
              }

              .indicators-container-tailscale {
                display: flex;
                align-items: center;
                gap: 4px;
              }
            </style>
            <ul class="list list-gap-10 collapsible-container" data-collapse-after="{{ .Options.IntOr "collapseAfter" 3 }}">
              {{ range .JSON.Array "devices" }}
              <li>
                <div class="flex items-center gap-10">
                  <div class="device-name-container-tailscale grow">
                    <span class="size-h4 block text-truncate color-primary">
                      {{ findMatch "^([^.]+)" (.String "name") }}
                    </span>
                    <div class="indicators-container-tailscale">
                      {{ if and (not ($.Options.BoolOr "disableUpdateIndicator" false)) (.Bool "updateAvailable") }}
                      <span class="update-indicator-tailscale" data-popover-type="text" data-popover-text="Update Available"></span>
                      {{ end }}

                      {{ if not ($.Options.BoolOr "disableOfflineIndicator" false) }}
                      {{ $lastSeen := .String "lastSeen" | parseTime "rfc3339" }}
                      {{ if not ($lastSeen.After (offsetNow "-10s")) }}
                      {{ $lastSeenTimezoned := $lastSeen.In now.Location }}
                      <span class="offline-indicator-tailscale" data-popover-type="text"
                        data-popover-text="Offline - Last seen {{ $lastSeenTimezoned.Format " Jan 2 3:04pm" }}"></span>
                      {{ end }}
                      {{ end }}

                    </div>
                  </div>
                </div>
                <div class="device-info-container-tailscale">
                  <ul class="list-horizontal-text device-info-tailscale">
                    <li>{{ .String "os" }}</li>
                    <li>
                      {{ if and ($.Options.BoolOr "prioritiseTags" false) (.Exists "tags.0") }}
                        {{ trimPrefix "tag:" (.String "tags.0") }}
                      {{ else }}
                        {{ .String "user" }}
                      {{ end }}
                    </li>
                  </ul>
                  <div class="device-ip-tailscale">
                    {{ .String "addresses.0"}}
                  </div>
                </div>
              </li>
              {{ end }}
            </ul>

        # - type: group
        #   widgets:
        #     - type: hacker-news
        #     - type: lobsters

        # - type: videos
        #   channels:
        #     - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
        #     - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
        #     - UCsBjURrPoezykLs9EqgamOA # Fireship
        #     - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
        #     - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

        # - type: group
        #   widgets:
        #     - type: reddit
        #       subreddit: technology
        #       show-thumbnails: true
        #     - type: reddit
        #       subreddit: selfhosted
        #       show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: Montreal, Canada
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        
        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            - go-gitea/gitea
            - immich-app/immich
            - syncthing/syncthing
